export const enum RouteType {
    None = 0,
    LevelGe = 1,
    LevelLe = 2,
    ShipSumGe = 3,
    ShipSumLe = 4,
    ShipTypeGe = 5,
    ShipTypeLe = 6,
    FlagShipLevelGe = 9,
    FlagShipLevelLe = 10,
    FlagShipType = 11,
    SpyGe = 14,
    FlagShipSpeedGe = 15,
    FlagShipSpeedLe = 16,
    SpeedMinGe = 17,
    SpeedMinLe = 18,
    SpeedMaxGe = 19,
    SpeedMaxLe = 20,
    SpeedAvgGe = 21,
    SpeedAvgLe = 22,
    LuckyGe = 27,
    LuckyLe = 28,

}