export enum NodeType{
Reward=3,
Loss=5,
Hide=6,
Boss=2,
AirAttack=10,
SpecialPoint=11,
SpecialBoss=14,
PushBuffPoint=13,
Figth=1,
Null=4,
LittleBoss=7,
}
export const NodeTypeOption=[
{label:"获得资源",value:3},
{label:"失去资源",value:5},
{label:"未知",value:6},
{label:"Boss",value:2},
{label:"空战",value:10},
{label:"特殊",value:11},
{label:"特殊Boss",value:14},
{label:"获得Buff",value:13},
{label:"战斗",value:1},
{label:"空",value:4},
{label:"小Boss",value:7},
]
